### ISSUE TITLE
えらー

### ISSUE THREAD

**Issue by gamesukimanIRS** [gamesukimanIRS/eturan-only#1]
ParseError: "Invalid numeric literal" (EXCEPTION) in "/plugins/NozamaPlime-v1.0.0/src/NozamaPlime/Main" at line 18

**Comment by Momiji0319** [comment]
mkdir($this->getDataFolder(), 0788, true);
にすれば動くかと

**Comment by gamesukimanIRS** [comment]
[壁]｀･ω･´)b ﾃﾝｷｭ
